### ISSUE TITLE
No `theta_0` parameter used in Exercise 2 Regularized Logistic Regression

### ISSUE THREAD

**Issue by hilmandayo** [JWarmenhoven/Coursera-Machine-Learning#2]
Hi. 
I am right now doing Andrew Ng. class (Machine Learning) and am using your answer as a guidance. I've realized something in your Exercise 2 (the regularized exercise one).

You've extracted your data from the `ex2data2.txt` like this:

```
data2 = loaddata('data/ex2data2.txt', ',')
y = np.c_[data2[:,2]]
X = data2[:,0:2]
```

And I believe you didn't inserted the `theta_0` parameter to the `X` variable's first column (supposed to be the value of 1). Aren't it supposed to be so? In the non-regularized logistic regression exercise, you did inserted the `theta_0` parameter as like this:

```
X = np.c_[np.ones((data.shape[0],1)), data[:,0:2]]
```

Am I missing something here?

**Comment by JWarmenhoven** [comment]
Hi,

Good question! 
The features (X) loaded in the regularized logistic regression exercise are transformed into a set of polynomial features (XX) using the [`preprocessing.PolynomialFeatures`](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html#sklearn.preprocessing.PolynomialFeatures) function from scikit-learn. By default, this function will insert a column with ones for the bias/intercept (`include_bias=True`).

I probably should have clarified that in the notebook.
Edit: I have updated the notebook.
